// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dbapp.Data;

#nullable disable

namespace DbApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250108180711_123")]
    partial class _123
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("dbapp.Data_classes.Contract", b =>
                {
                    b.Property<int>("ContractID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("contractPDF")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("ContractID");

                    b.ToTable("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
